frnd1 = input("Enter Your Friends Birthdate  ")
print("Your Friends Birthdate is : ", frnd1)
frnd2 = input("Enter Your Friends Birthdate  ")
print("Your Friends Birthdate is : ", frnd2)
frnd3 = input ("Enter Your Friends Birthdate ")
print("Your Friends Birthdate is : ", frnd3)
frnd4 = input("Enter Your Friends Birthdate  ")
print("Your Friends Birthdate is : ", frnd4)
frnd5 = input("Enter Your Friends Birthdate  ")
print("Your Friends Birthdate is : ", frnd5)